## 什么是 NumPy?  
NumPy是一个功能强大的Python库，主要用于对多维数组执行计算。NumPy这个词来源于两个单词-- Numerical和Python。NumPy提供了大量的库函数和操作，可以帮助程序员轻松地进行数值计算。这类数值计算广泛用于以下任务：  

**机器学习模型：**  在编写机器学习算法时，需要对矩阵进行各种数值计算。例如矩阵乘法、换位、加法等。NumPy提供了一个非常好的库，用于简单(在编写代码方面)和快速(在速度方面)计算。NumPy数组用于存储训练数据和机器学习模型的参数。

**图像处理和计算机图形学：** 计算机中的图像表示为多维数字数组。NumPy成为同样情况下最自然的选择。实际上，NumPy提供了一些优秀的库函数来快速处理图像。例如，镜像图像、按特定角度旋转图像等。

**数学任务：**  NumPy对于执行各种数学任务非常有用，如数值积分、微分、内插、外推等。因此，当涉及到数学任务时，它形成了一种基于Python的MATLAB的快速替代。

Numpy数据结构在以下方面表现更好：  

1.内存大小—Numpy数据结构占用的内存更小。  

2.性能—Numpy底层是用C语言实现的，比列表更快。  

3.运算方法—内置优化了代数运算等方法。  

简而言之，Numpy在性能上比起Python自带的数组（列表）有很大的提升。在数据量小的场景可能不太明显，但是随着处理数据量的提升，Numpy可以带来成倍的性能提高。所以Numpy是现在数据处理必备的工具。

**关于先学基础知识还是先动手做项目。各有利弊，先学知识可能看了很多，但是并不知道有什么实际用处，往往也没深刻印象。如果先动手做项目，又会不断遇到不了解的基础知识，学习过程不断被打断。最后只能结合吧。先快速了解基础知识，然后动手做项目，遇到忘了或者没了解过的知识，再查找资料。最后还是那个老结论，多做多用就记住了。**

### NumPy 的安装  
和大多数Python额外的module一夜，在计算机上安装NumPy的最快也是最简单的方法是在shell上使用以下命令：pip install numpy。

In [14]:
import numpy as np     # 引入numpy模块，名命为np
print(np.__version__)  # 查看一下版本号

1.23.4


### NumPy的数组  
NumPy提供的最重要的数据结构是一个称为NumPy数组的强大对象。NumPy数组是通常的Python数组的扩展。NumPy数组配备了大量的函数和运算符，可以帮助我们快速编写上面讨论过的各种类型计算的高性能代码。

### Numpy数组的初始化

In [15]:
# 创建一维数组
a = np.array([0, 1, 2, 3, 4])
b = np.array(("a","b","c","d","e","f","g","h"))
c = np.arange(5)
d = np.linspace(0, 2*np.pi, 5)  # linespace函数生成一个等间隔数字序列，linespace(start,end,total)

print(a) # >>>[0 1 2 3 4]
print(b) # >>>['a' 'b' 'c' 'd' 'e' 'f' 'g' 'h']
print(c) # >>>[0 1 2 3 4]
print(d) # >>>[ 0.          1.57079633  3.14159265  4.71238898  6.28318531]
print(a[3]) # 访问数组指定下标元素，数组下标从0开始

e = np.full((3, 3), True, dtype=bool)
# > array([[ True,  True,  True],
# >        [ True,  True,  True],
# >        [ True,  True,  True]], dtype=bool)
print(e)

# Alternate method:
f = np.ones((3,3), dtype=bool)
print(f)

[0 1 2 3 4]
['a' 'b' 'c' 'd' 'e' 'f' 'g' 'h']
[0 1 2 3 4]
[0.         1.57079633 3.14159265 4.71238898 6.28318531]
3
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [4]:
# 创建二维数组
a = np.array([[11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20],
              [21, 22, 23, 24, 25],
              [26, 27, 28 ,29, 30],
              [31, 32, 33, 34, 35]])
 
print(a[2,4]) # 访问数组指定下标元素，数组下标从0开始

25


在Numpy的ndarray中，原则上是不支持增加或者删除数组的元素的（这样才能有比较好的性能）。另外，numpy的ndarray的同一个数组，也不支持不同的数据类型。这样每个数组元素，占据的空间一致。这样尤其在处理数字数据的时候，可以有最好的性能。  

ndarray有append和delete操作，但是这种操作实际不是修改了原始数组，而是重新创建了一个新数组。这样在数组规模很大的时候，耗时非常大。所以尽量不要使用。  


In [5]:
# 创建原始数组
arr = np.array([1, 2, 3])
print("Original array:", arr)

# 添加元素
arr = np.append(arr, [4, 5])
print("After append:", arr)

# 删除元素
arr = np.delete(arr, 1)  # 删除索引为1的元素
print("After delete:", arr)

Original array: [1 2 3]
After append: [1 2 3 4 5]
After delete: [1 3 4 5]


In [ ]:
Numpy的ndarray和Phthon的数组（list）可以互相转换。

In [7]:
# Python 列表
python_list = [1, 2, 3, 4, 5]

# 转换为 NumPy 数组
numpy_array = np.array(python_list)

print(numpy_array)
print(type(numpy_array))

# Python 列表的列表
python_list_of_lists = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

# 转换为二维 NumPy 数组
numpy_2d_array = np.array(python_list_of_lists)

print(numpy_2d_array)

# NumPy 数组
numpy_array = np.array([1, 2, 3, 4, 5])

# 转换为 Python 列表
python_list = numpy_array.tolist()

print(python_list)
print(type(python_list))

# 二维 NumPy 数组
numpy_2d_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# 转换为 Python 列表的列表
python_list_of_lists = numpy_2d_array.tolist()

print(python_list_of_lists)


[1 2 3 4 5]
<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1, 2, 3, 4, 5]
<class 'list'>
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


### 数组的切片访问

In [8]:
a = np.array([[11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20],
              [21, 22, 23, 24, 25],
              [26, 27, 28 ,29, 30],
              [31, 32, 33, 34, 35]])

print(a)

# MD slicing
print(a[0, 1:4])  # 第0行，第1到第3个元素（不包括4）
print(a[1:4, 0])  # 第1到第3行，第0个元素
print(a[::2,::2]) # 全部行列，步长2选取元素
print(a[:, 1])    # 全部行，第一列

[[11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]]
[12 13 14]
[16 21 26]
[[11 13 15]
 [21 23 25]
 [31 33 35]]
[12 17 22 27 32]


### 数组属性   
在使用 NumPy 时，你会想知道数组的某些信息。很幸运，在这个包里边包含了很多便捷的方法，可以给你想要的信息。  

In [10]:
a = np.array([[11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20],
              [21, 22, 23, 24, 25],
              [26, 27, 28 ,29, 30],
              [31, 32, 33, 34, 35],
              [36, 37, 38, 39, 40],
              [41, 42, 43, 44, 45]])

print(type(a))     # >>><class 'numpy.ndarray'>
print(a.dtype)     # >>>int32
print(a.shape)     # >>>(7, 5)
print(a.size)      # >>>元素个数，行x列=35
print(a.itemsize)  # 表示数组中每个元素的大小，以字节为单位。int32是4个字节
print(a.ndim)      # >>>数组的维数
print(a.nbytes)    # >>> 数组总字节数，35*4 = 140

<class 'numpy.ndarray'>
int32
35
(7, 5)
4
2
140


### 改变数组形状和数组整体计算

In [20]:
# Basic Operators
a = np.arange(25)   
print("一维数组：")
print(a)
a = a.reshape((5, 5))  # 变为二维数组
print("变成二维数组：")
print(a)

b = np.array([10, 62, 1, 14, 2, 56, 79, 2, 1, 45,
              4, 92, 5, 55, 63, 43, 35, 6, 53, 24,
              56, 3, 56, 44, 78])
print("一维数组：")
print(b)
b = b.reshape((5,5))
print("变成二维数组：")
print(b)

print("每个位置加一个值：")
print(a + 3)
print("每个位置求平方：")
print(a ** 2)

print("每个对应位置求和：")
print(a + b)
print("每个对应位置求差：")
print(a - b)
print("每个对应位置求积：")
print(a * b)
print("每个对应位置求商：")
print(a / b)
print("每个对应位置比较：")
print(a < b) 
print("每个对应位置比较：")
print(a > b)
print("两个矩阵求点积：")
print(a.dot(b))

print("菲矩形矩阵求点积：")
c = np.arange(12)
c1 = c.reshape((3,4))
c2 = c.reshape((4,3))
print(c1.dot(c2))


a = a.reshape((1,25))  # 用-1，表示全部元素
print("变成一维数组：")
print(a)
c = c.reshape((2,-1))  # 可以有一维使用-1
print(c)
print("元素数量不对，会出错：")
a = a.reshape((4,6))

一维数组：
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
变成二维数组：
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
一维数组：
[10 62  1 14  2 56 79  2  1 45  4 92  5 55 63 43 35  6 53 24 56  3 56 44
 78]
变成二维数组：
[[10 62  1 14  2]
 [56 79  2  1 45]
 [ 4 92  5 55 63]
 [43 35  6 53 24]
 [56  3 56 44 78]]
每个位置加一个值：
[[ 3  4  5  6  7]
 [ 8  9 10 11 12]
 [13 14 15 16 17]
 [18 19 20 21 22]
 [23 24 25 26 27]]
每个位置求平方：
[[  0   1   4   9  16]
 [ 25  36  49  64  81]
 [100 121 144 169 196]
 [225 256 289 324 361]
 [400 441 484 529 576]]
每个对应位置求和：
[[ 10  63   3  17   6]
 [ 61  85   9   9  54]
 [ 14 103  17  68  77]
 [ 58  51  23  71  43]
 [ 76  24  78  67 102]]
每个对应位置求差：
[[-10 -61   1 -11   2]
 [-51 -73   5   7 -36]
 [  6 -81   7 -42 -49]
 [-28 -19  11 -35  -5]
 [-36  18 -34 -21 -54]]
每个对应位置求积：
[[   0   62    2   42    8]
 [ 280  474   14    8  405]
 [  40 1012   60  715  882]
 [ 645  560  102  954  456]
 [1120   63 1232 1012 1872]]
每个对应位

ValueError: cannot reshape array of size 25 into shape (4,6)

### 数组特殊运算符
NumPy还提供了一些别的用于处理数组的好用的运算符。

In [8]:
import numpy as np

# 创建数组
arr = np.array([0, 1.5, 2.5, 3.5, 4.5])

# 应用方法
print("Sum:", arr.sum())                   # 求和
print("Mean:", arr.mean())                 # 求平均
print("Standard Deviation:", arr.std())    # 求标准差
print("Variance:", arr.var())              # 求方差   
print("Minimum:", arr.min())               # 求最小值   
print("Maximum:", arr.max())               # 求最大值 
print("Index of Minimum:", arr.argmin())   # 求最小值的索引位置
print("Index of Maximum:", arr.argmax())   # 求最大值的索引位置
print("Product of Elements:", arr.prod())  # 求乘积
print("Cumulative Sum:", arr.cumsum())     # 求连续和 
print("Cumulative Product:", arr.cumprod())# 求连续积
print("All True:", arr.all())              # 全部为True（非0） 
print("Any True:", arr.any())              # 最少一个为True（非0）
print("Clipped Array:", arr.clip(2, 4))    # 将所有值限定在指定范围内
print("Rounded Array:", arr.round(1))      # 将所有数值四舍五入到指定位小数

Sum: 12.0
Mean: 2.4
Standard Deviation: 1.5620499351813308
Variance: 2.44
Minimum: 0.0
Maximum: 4.5
Index of Minimum: 0
Index of Maximum: 4
Product of Elements: 0.0
Cumulative Sum: [ 0.   1.5  4.   7.5 12. ]
Cumulative Product: [0. 0. 0. 0. 0.]
All True: False
Any True: True
Clipped Array: [2.  2.  2.5 3.5 4. ]
Rounded Array: [0.  1.5 2.5 3.5 4.5]


In [ ]:
### 数值条件索引
可以在数值下标的【】中写入一个条件，会返回所有满足条件的元素。
可以使用where，返回的是满足条件的元素的下标

In [16]:
a = np.array([0,1,2,4,5,6,8,10,12,13,15,17,19,20,21])
print(a)
b = a[a>12]    # 找出大于12的元素
print(b)
c = a[a%3==1]  # 找出模3余1的元素
print(c)

# 使用条件索引修改元素
a[a % 2 == 1] *= 3  # 所有奇数*3
print(a)

# Where，
a = np.arange(0, 100, 10)
b = np.where(a < 50) 
c = np.where(a >= 50)[0]
print(b) # >>>(array([0, 1, 2, 3, 4]),)
print(c) # >>>[5 6 7 8 9]

[ 0  1  2  4  5  6  8 10 12 13 15 17 19 20 21]
[13 15 17 19 20 21]
[ 1  4 10 13 19]
[ 0  3  2  4 15  6  8 10 12 39 45 51 57 20 63]
(array([0, 1, 2, 3, 4], dtype=int64),)
[5 6 7 8 9]


### 两个数组交互操作

In [23]:
# 水平叠加两个数组
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
print(a)
print(b)

# Answers
# Method 1:
c = np.concatenate([a, b], axis=1)
print(c)

# Method 2:
d = np.hstack([a, b])
print(d)

# Method 3:
e = np.c_[a, b]
print(e)


# Method 4:
f = np.r_[a, b]
print(f)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]
[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]
[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]
[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [22]:
# 数组自己重复
a = np.array([1,2,3])
print(a)

b = np.repeat(a, 3)  # 每个元素重复3次
print(b)

c = np.tile(a, 3)    # 整个数组重复3次
print(c)

d = np.r_[b,c]       # 连接数组
print(d)

[1 2 3]
[1 1 1 2 2 2 3 3 3]
[1 2 3 1 2 3 1 2 3]
[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


In [27]:
# 获取两个numpy数组之间的公共项，就是在两个数组中都出现的元素
a = np.array([1,8,3,2,3,4,3,4,5,6])
b = np.array([6,2,10,2,7,4,9,4,9,8])

c = np.intersect1d(a,b) 
print(c)

[2 4 6 8]


In [29]:
# 从一个数组中删除存在于另一个数组中的项
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,3,9])

c = np.setdiff1d(a,b)
print(c)

[1 2 4]


In [31]:
# 得到两个数组元素匹配的位置
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,5,8])

c = np.where(a == b)
print(c)

(array([1, 3, 5, 7, 8], dtype=int64),)


In [ ]:
# 从numpy数组中提取给定范围内的所有数字
a = np.arange(15)

# Method 1
index = np.where((a >= 5) & (a <= 10))
b = a[index]
print(b)

# Method 2:
index = np.where(np.logical_and(a>=5, a<=10))
c = a[index]
print(c)
# > (array([6, 9, 10]),)

# Method 3: (thanks loganzk!)
a[(a >= 5) & (a <= 10)]

In [34]:
# 交换二维numpy数组中的两(行）列
# Input
a = np.arange(9).reshape(3,3)
print(a)

b = a[[1,0,2], :]
print(b)

# Solution
c = a[:, [1,0,2]]
print(c)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[3 4 5]
 [0 1 2]
 [6 7 8]]
[[1 0 2]
 [4 3 5]
 [7 6 8]]
